import type { Metadata } from "next";
import "../styles/globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import Image from "next/image";
import bs from "./../../public/bs3.svg"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <header>
          <Navbar />
        </header>

        <main className="min-h-screen">{children}</main>

        <footer>
          <Footer />
        </footer>

        {/* Logo fijo en la esquina inferior derecha */}
        <div className="fixed bottom-8 right-4 z-50 bg-black/60 rounded-full">
          <Image src={bs} alt="Logo" width={40} height={40} />
        </div>
      </body>
    </html>
  );
}
