import type { Metadata } from "next";
import "../styles/globals.css"
import Navbar from "@/components/Navbar";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body >
        <header>
          <Navbar/>
        </header>

        <main className="min-h-screen">{children}</main>

        <footer>
          
        </footer>
      </body>
    </html>
  );
}
